---
- name: Create Cri Tools Temporary Path
  file:
    path: "{{ temporary_dirs }}cri-tools"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory

- name: Get Crictl Binary File
  shell: "export http_proxy={{ http_proxy }} ; export https_proxy={{ https_proxy }} ; wget -qO- 'https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ cri_tools_version }}/crictl-{{ cri_tools_version }}-{{ os_drive }}-{{ os_arch }}.tar.gz' | tar zx -C {{ temporary_dirs }}cri-tools"
  ignore_errors: true