---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: local-task }
    
- hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  tasks:
    - name: Check all Nodes
      ping: 

- name: Initialize Crane Env
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'etcd_certifcate_rotation'
    crane_tasks: 'etcd-ca-rotation'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }
    
- name: Initialize SSH Secret Key
  hosts: k8s-cluster:etcd
  gather_facts: false
  become: yes
  become_method: sudo
  vars_files:
    - "roles/crane/defaults/main.yml"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

- name: Create New CA
  hosts: etcd[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/etcd-cluster-management/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/etcd-cluster-management/defaults/tls.yaml"
  roles:
    - { role: etcd-ca-rotation, tags: [etcd-ca-rotation]}

- name: Update Etcd Cluster Server Config
  hosts: etcd-cluster
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  tasks:
    - { include: 'roles/etcd-ca-rotation/includes/update-cluster-etcd.yml' }

- name: Update Kubernetes Cluster ApiServer Server Config
  hosts: k8s-master
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include: 'roles/etcd-ca-rotation/includes/update-cluster-apiserver.yml' }

- name: Turn on Cluster Scheduling
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  tasks:
    - { include: 'roles/kubernetes-upgrade/includes/check-cluster-pod.yaml' }

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'etcd_certifcate_rotation'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include: 'roles/crane/includes/sync-crane.yaml' }