---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: local-task }

- name: Initialize Crane Env
  hosts: all
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'migration_k8s_to_new_etcd_cluster'
    crane_tasks: 'migration_k8s_to_new_etcd_cluster'
  vars_files:
    - "roles/cri-install/vars/containerd.yaml"
    - "roles/cri-install/vars/crio.yaml"
    - "roles/cri-install/vars/docker.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
  roles:
    - { role: crane, tags: [crane] }

- name: Initialize SSH Secret Key
  hosts: etcd-new-cluster[0]
  gather_facts: false
  become: yes
  become_method: sudo
  vars_files:
    - "roles/crane/defaults/main.yml"
  roles:
    - { role: downloads-ssh-key, tags: [copy_ssh_private_key]}

- hosts: kube-master
  gather_facts: false
  become: yes
  become_method: sudo
  vars_files:
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  tasks:
    - { include: 'roles/etcd-cluster-management/includes/initialize-etcd-home.yaml' }

- name: Deploy New Etcd Cluster TLS to Kubernetes Master
  hosts: etcd-new-cluster[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/etcd-cluster-management/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/kubernetes-cluster-management/vars/haproxy.yaml"
    - "roles/kubernetes-networks/defaults/keepalived.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  tasks:
    - { include: 'roles/etcd-cluster-management/includes/etcd-new-cluster/copy-new-etcd-cluster-tls-to-master.yaml' }

- name: Deploy apiServer Manifests
  hosts: kube-master
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/etcd-cluster-management/vars/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/system-initialize/defaults/main.yml"
    - "roles/kubernetes-cluster-management/vars/haproxy.yaml"
    - "roles/kubernetes-networks/defaults/keepalived.yaml"
    - "roles/crane/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
  tasks:
    - { include: 'roles/etcd-cluster-management/includes/etcd-new-cluster/deploy-new-apiserver-mainifests.yaml' }

- name: Kubernetes Cluster Setup
  hosts: kube-master[0]
  gather_facts: true
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
  vars_files:
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/crane/defaults/main.yml"
    - "roles/etcd-cluster-management/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
    - "roles/kubernetes-cluster-management/defaults/main.yml"
  tasks:
    - { include: 'roles/etcd-cluster-management/includes/etcd-new-cluster/k8s-set-labels.yaml' }

- name: Sync Crane Delploy Files to Instance
  hosts: kube-master[0]
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true
    crane_deploy_type: 'main'
  vars_files:
    - "roles/crane/defaults/main.yml"
    - "roles/downloads-ssh-key/defaults/main.yml"
    - "roles/kubernetes-manifests/defaults/main.yml"
    - "roles/kubernetes-cluster-management/defaults/configure.yaml"
  tasks:
    - { include: 'roles/crane/includes/sync-crane.yaml' }