---

- name: Copy Limit Config
  template:
    src: "roles/system-initialize/templates/19-k8s-limit.conf"
    dest: "/etc/security/limits.d/19-k8s-limit.conf"
    owner: "{{ ssh_connect_user }}"
    mode: 0644
  ignore_errors: true