---

- name: Create Other Path
  file:
    path: "{{ temporary_dirs }}tools"
    owner: "{{ ssh_connect_user }}" 
    mode: 0755
    state: directory
  ignore_errors: true

- name: Clean Cfssl files
  shell: "mv {{ kubernetes_ctl_path }}{{ item }} {{ temporary_dirs }}tools"
  with_items:
    - "cfssl"
    - "cfssljson"
  when: is_remove_all or is_remove_cfssl
  ignore_errors: true

- name: Clean Temporary files
  shell: "rm -rf {{ temporary_dirs }}"
  when: is_remove_temporary
  ignore_errors: true

- name: Clean Limit
  shell: "rm -rf /etc/security/limits.d/19-k8s-limit.conf"
  when: is_remove_all
  ignore_errors: true