# Calico Type 
# Calico 使用的模式默认使用, 默认 IPIP 设置为 :Always, 如果需要使用 BGP 设置为 Off:, 
calico_type: 'Always'

# Calico CNI Version
# Calico 使用 CNI 版本
calico_cni_version: '0.3.1'

# Calico Release 配置文件
## https://docs.projectcalico.org/manifests/calico.yaml
## Docs https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options