---

- name: Move SSH Known
  shell: "mv ~/.ssh/known_hosts ~/.ssh/known_hosts-`date +%Y%m%d%H%M%S`"
  ignore_errors: true

- name: Set SSH UseDNS
  shell: 
    sed -ri 's/^#(UseDNS )yes/\1no/' /etc/ssh/sshd_config
  ignore_errors: true