## Systemd Config
## ********************************************************************************************************************************

# Systemd 子配置文件目录
systemd_etc_dirs: '/etc/systemd/system/'

# Systemd 主配置文件目录
systemd_default_dirs: '/lib/systemd/system/'

# 内核 nf_conntrack 32GB 配置
# kernel_nf_conntrack_buckets: 262144
# kernel_nf_conntrack_max: 1048576

# 内核 nf_conntrack 64GB 配置
kernel_nf_conntrack_buckets: 1048576
kernel_nf_conntrack_max: 4194304

# chrony 上游时区服务器
# 如果没有公网地址, 请自行修改
is_chrony_deploy: false
chrony_sync_server: ["cn.pool.ntp.org", "time.cloudflare.com"]

# 检查命令 chronyc sources -v