---
- name: Copy Kubernetes DNS Config Files
  template: 
    src: "roles/kubernetes-networks/templates/CoreDNS.j2"
    dest: "{{ temporary_dirs }}main/CoreDNS.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}"

- name: Deploy CoreDNS
  shell: '{{ kubernetes_ctl_path }}kubectl apply -f {{ temporary_dirs }}main/CoreDNS.yml'
  when: is_kube_dns
  ignore_errors: true

- name: Copy Kubernetes Proxy Config Files
  template: 
    src: "roles/kubernetes-networks/templates/kube-proxy.j2"
    dest: "{{ temporary_dirs }}main/kube-proxy.yml"
    mode: 0644
    owner: "{{ ssh_connect_user }}"

- name: Deploy Kube-Proxy
  shell: '{{ kubernetes_ctl_path }}kubectl apply -f {{ temporary_dirs }}main/kube-proxy.yml'
  when: is_kube_proxy
  ignore_errors: true

- name: Deploy General Networks
  include: 'roles/kubernetes-networks/includes/{{ general_network_drive }}.yaml'
  when: general_network_drive != 'none'