---

- name: Create Crane Tools Temporary Directory
  file:
    path: "{{ temporary_dirs }}scripts"
    mode: 0755
    owner: "{{ ssh_connect_user }}"
    state: directory

- name: Copy Crane tools Script Path
  template:
    src: "roles/crane/templates/{{ item }}"
    dest: "{{ temporary_dirs }}scripts/{{ item }}"
    owner: "{{ ssh_connect_user }}"
    mode: 0755
  with_items:
  - "load_containerd_binary.sh"
  - "load_containerd_images.sh"
  - "load_docker_images.sh"
  - "load_docker_binary.sh"
  - "reload_docker_kubelet.sh"
  - "clean_network_filter.sh"
  - "etcd.sh"